project:
  name: stage-holaplex-hub
  domain: holaplex.dev

vpc:
  name: main
  routing: REGIONAL
  region: us-central1

nat:
  name: nat

router:
  name: router

subnetwork:
  name: private
  privateIpGoogleAccess: true
  cidrRange: "10.0.0.0/18"

kubernetes:
  name: stage-holaplex-usc-gke
  environment: staging
  zones: [us-central1-a, us-central1-b, us-central1-c]
  autoscaling:
   enabled: true
  nodePools:
    - name: amd64
      machineType: n2-standard-8
      diskSizeGb: 250
      zones: [us-central1-a]
      #Node count per AZ.
      nodeCount: 1
      autoscaling:
        min: 1
        max: 2
    - name: arm64
      zones: [us-central1-a]
      machineType: t2a-standard-8
      diskSizeGb: 250
      nodeCount: 1
      autoscaling:
        min: 1
        max: 2
  loadBalancer:
    enabled: false
  networkPolicies:
    enabled: true
  networkRanges:
    pods: "10.48.0.0/14"
    services: "10.52.0.0/20"
  backups:
    service:
      name: velero
      namespace: velero
    bucket:
      name: stage-holaplex-usc-gke-velero
      location: us
      storageClass: MULTI_REGIONAL
  logging:
    service:
      name: logging
      namespace: logging
    bucket:
      name: stage-holaplex-usc-gke-logs
      location: us
      storageClass: MULTI_REGIONAL


sqlInstances: []
